siteTitle="Emily Young"
siteUrl="http://livingincircuits.co.uk"
description="Emily Young is a UX Designer/Developer from Yorkshire"
blogUrl = "http://livingincircuits.co.uk/"
blogTitle = "Living In Circuits"
blogAuthor = "Emily Young"
blogDescr = "Emily Young is a UX Designer/Developer from Yorkshire"
