siteTitle="Living In Circuits"
siteUrl="http://livingincircuits.co.uk"
description="Emily Young is a UX Designer/Developer from Yorkshire who loves to create clean, simple and inclusive experiences"
blogUrl = "http://livingincircuits.co.uk/"
blogTitle = "Living In Circuits"
blogAuthor = "Emily Young"
blogDescr = "Emily Young is a UX Designer/Developer from Yorkshire who loves to create clean, simple and inclusive experiences"
