siteTitle="Living In Circuits"
siteUrl="https://livingincircuits.co.uk"
description="Emily Young is a UX Designer/Developer from Yorkshire who loves to create clean, simple and inclusive experiences"
blogUrl = "https://livingincircuits.co.uk/"
blogTitle = "Living In Circuits"
blogAuthor = "Emily Young"
blogDescr = "Emily Young is a UX Designer/Developer from Yorkshire who loves to create clean, simple and inclusive experiences"
